### ISSUE TITLE
Consider using Pagic to build the website?

### ISSUE THREAD

**Issue by xcatliu** [reno-router/reno#3]
[Pagic](https://pagic.org) is a static site generator powered by Deno + React

Here are some demos:

- [pagic.org](https://pagic.org)
- [Deno X ranking](https://yoshixmk.github.io/deno-x-ranking/)
- [TypeScript 入门教程](https://ts.xcatliu.com/)

Ask me anything if you have some problem.

**Comment by jamesseanwright** [comment]
I've been toying with building a website for Reno, so I'll certainly consider Pagic if I go ahead. Great project!
