### ISSUE TITLE
withQueryString Method

### ISSUE THREAD

**Issue by tracker1** [reno-router/reno#5]
Would be nice to have a typed withQueryString method, similar to the withJsonBody or withFormBody, but for parsing/typing query string parameters.

**Comment by jamesseanwright** [comment]
Thanks for the suggestion @tracker1! It's an interesting idea, but I'm not sure if it's necessary given that `withQueryString` would need a mapping to understand how the values of each param should be parsed; this is relatively straightforward, but given the need for said mapping it might not provide much benefit over doing such parsing imperatively.

Do you have a particular use case that would benefit from this feature?

Cheers!

**Comment by jamesseanwright** [comment]
I'm going to close this for now, but please feel free to reopen if you'd like to discuss this further.

**Comment by tracker1** [comment]
Mainly for completeness sake... since I often will be parsing query string parameters as, for example search filters in API requests and it would help to have a consistent interface to return the 422 when disallowed/unexpected/out of range parameters are passed in the querystring similar to a JSON or form body post.

**Comment by jamesseanwright** [comment]
Please could you give me an example of the sort of query string you'd want to parse? It'd help me determine how `withQueryString` could be designed.

**Comment by jamesseanwright** [comment]
I'm going to close this due to lack of activity. Feel free to reopen, whenever you have the time, with an example of a query string you'd like to parse so I can consider how the API should look (beyond fundamentally being a higher-order route handler).
