### ISSUE TITLE
Suggestion: implement route params instead of regex

### ISSUE THREAD

**Issue by winston0410** [reno-router/reno#71]
Hi, thanks for this clean and minimal router! One thing I think that can be implemented is route params, like :id or {id}. Regex is powerful, but really verbose to write and could be hard to read, and for a route, regex is not that useful I think.

What do you think?

**Comment by winston0410** [comment]
Sorry I didnt notice that there is a `*` syntax already, that should do the trick already!

**Comment by jamesseanwright** [comment]
Hey @winston0410! I am actually considering working on a new major iteration of Reno to replace the current path parser with [`URLPattern`](https://developer.mozilla.org/en-US/docs/Web/API/URLPattern), which landed in Deno v1.15; this will simplify the routing implementation and will provide a more familiar means of expressing routes. Keep your eyes peeled!

**Comment by winston0410** [comment]
> Hey @winston0410! I am actually considering working on a new major iteration of Reno to replace the current path parser with [`URLPattern`](https://developer.mozilla.org/en-US/docs/Web/API/URLPattern), which landed in Deno v1.15; this will simplify the routing implementation and will provide a more familiar means of expressing routes. Keep your eyes peeled!

That will be perfect if you can upgrade it with that! Thanks!
